# Generated by Django 6.0.6 on 2026-07-04 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_default_tenant(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Tenant = apps.get_model('core', 'Tenant')
    UserProfile = apps.get_model('core', 'UserProfile')
    Category = apps.get_model('core', 'Category')
    Product = apps.get_model('core', 'Product')
    Customer = apps.get_model('core', 'Customer')
    Invoice = apps.get_model('core', 'Invoice')
    StockMovement = apps.get_model('core', 'StockMovement')

    users = User.objects.all()
    if not users.exists():
        return

    # Create a default tenant for the first user
    default_user = users.first()
    default_tenant = Tenant.objects.create(name=f"{default_user.username}'s Store")

    # Create UserProfile for all existing users and assign them to the default tenant
    for user in users:
        UserProfile.objects.get_or_create(user=user, defaults={'tenant': default_tenant})

    # Associate all existing data to this default tenant
    Category.objects.all().update(tenant=default_tenant)
    Product.objects.all().update(tenant=default_tenant)
    Customer.objects.all().update(tenant=default_tenant)
    Invoice.objects.all().update(tenant=default_tenant)
    StockMovement.objects.all().update(tenant=default_tenant)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(populate_default_tenant),
    ]
